name: HACS validation

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: plugin
